### ISSUE TITLE
how does text extraction work ?

### ISSUE THREAD

**Issue by flippythemonster** [AlexanderPro/WindowTextExtractor#11]
Hi ! awesome work, I was wondering if the text extraction is fully based on OCR ? based on my testing, it seems to be the case since there are many confusions between 1 and l for example.

**Comment by flippythemonster** [comment]
thanks for the prompt response ! if I don't want to use OCR, how can I extract text? 
it seems that whenever I try to hover over an app, I get property related information instead of the textual content.
Sorry if I misunderstand the product!

**Comment by AlexanderPro** [comment]
You should download the latest version [2.0.0](https://github.com/AlexanderPro/WindowTextExtractor/releases/download/v2.0.0/WindowTextExtractor_v2.0.0.zip). Open "Text" tab and try to hover over an app for textual content. On "Image" tab you can see graphical window content and can grab it by "Grab" button.

**Comment by flippythemonster** [comment]
Please look at the attached picture:
![image](https://github.com/AlexanderPro/WindowTextExtractor/assets/153660019/f654ca76-4a08-4d52-90fb-fdc1b5934ebb)

This is the output when I try to hover over my chrome window, when I try on other apps, it does not output anything. And I am using the latest 2.0.0 version.

**Comment by flippythemonster** [comment]
Interesting, this works and fixes it. So it depends on whether the app supports UI automation or not ? I ve tried on other apps such as VScode, discord etc and run into similar trouble where these apps are recognised as chrome legacy windows. Are there other means to retrieve textual content from desktop without using OCR and is more global than UI automation ? 

I apologise if I am asking for redundant or stupid questions. I am trying to research for ways to do so but so far even state of the art OCR models have failed on my test cases.

**Comment by AlexanderPro** [comment]
Yes, some windows do not support UI automation. I could not find a universal solution for obtaining window text. Therefore, WindowTextExtractor contains several tabs. "Text" tab is for Microsoft UI Automation extracting and "Image" tab is for Microsoft Windows OCR extracting.

**Comment by flippythemonster** [comment]
oh thank you !! I am happy that you kept maintaining such project. Are you using tesseract for your OCR support ?

**Comment by AlexanderPro** [comment]
No, only Windows built-in OCR
