### ISSUE TITLE
[BUG] 2000/1024 character limit

### ISSUE THREAD

**Issue by God-damnit-all** [AlexanderPro/WindowTextExtractor#13]
WindowTextExtractor only retrieves the first 2000 characters in the "Text" tab.

In the Information tab, the "GetWindowText" function seems to be limited to 1024 characters (or maybe 1023).

The WM_GETTEXT function in the Information tab retrieves everything, however.

**Comment by AlexanderPro** [comment]
Hi @ImportTaste,

Thank you for finding the bug. I will try to fix it in the next version.

**Comment by AlexanderPro** [comment]
Please, try version [2.1.1](https://github.com/AlexanderPro/WindowTextExtractor/releases/download/v2.1.1/WindowTextExtractor_v2.1.1.zip)

**Comment by AlexanderPro** [comment]
Try version [2.1.2](https://github.com/AlexanderPro/WindowTextExtractor/releases/download/v2.1.2/WindowTextExtractor_v2.1.2.zip). If it does not fix the issue, please, attach the screenshot or give a program name.

**Comment by AlexanderPro** [comment]
Please, try version [2.1.3](https://github.com/AlexanderPro/WindowTextExtractor/releases/download/v2.1.3/WindowTextExtractor_v2.1.3.zip)
