### ISSUE TITLE
SmartMenuSystem disable alignment?

### ISSUE THREAD

**Issue by vicomannen** [AlexanderPro/WindowTextExtractor#14]
Hi!
This is not really an issue but more as a feature request. If I disable alignment in the settings, I was expecting it to be disabled also not only hidden. I want to disable it because Windows has its own window position memory, I want to let Windows take care of it. As long as SmartMenuSystem register the window positions it will be in "conflict" with OS's own window position memory e.g. next time you open same window after you have closed it, it will jump from one position to another just when you open it. Could you please make it possible to disable SMS alignment from registering window positions?

**Comment by AlexanderPro** [comment]
Hi @vicomannen,

As far as I know, Windows OS is responsible for this. When you start some process, its window is displayed in the position to which it was previously moved, whether manually or using SSM (SCM). Try to move and close the notepad window and start its process again. If I misunderstood you, please attach a video or gif file.
