### ISSUE TITLE
Application != open

### ISSUE THREAD

**Issue by Berserker4896** [AlexanderPro/WindowTextExtractor#2]
The zip file is unzip, but the file name "WindowTextExtractor64.exe" cannot open in both "Open" AND "Run as administrator".

**Comment by AlexanderPro** [comment]
Hi Berserker4896,

WindowTextExtractor64.exe is a special file. It is not for a manual run. It is located in WindowTextExtractor.exe resources and deleted when the main window closes. You should run only WindowTextExtractor.exe
