### ISSUE TITLE
watcher / streaming feature

### ISSUE THREAD

**Issue by Grabber** [AlexanderPro/WindowTextExtractor#3]
@AlexanderPro 
Is it possible to select one UI widget and receive data as more data is available (as a stream)?

**Comment by AlexanderPro** [comment]
Hi Grabber,

Sorry for the late response. Please, try version  [1.11.0](https://github.com/AlexanderPro/WindowTextExtractor/releases/download/v1.11.0/WindowTextExtractor_v1.11.0.zip)
