### ISSUE TITLE
Text collection function needed.

### ISSUE THREAD

**Issue by ohyungkr** [AlexanderPro/WindowTextExtractor#5]
I have one request.
When I get text by pointer, I want these texts to be stacked. need to not always refreshed.
I wish I could make the text stack and store without flush it in the with options button.

**Comment by AlexanderPro** [comment]
Hi Ohyung,

Please, try version  [1.13.0](https://github.com/AlexanderPro/WindowTextExtractor/releases/download/v1.13.0/WindowTextExtractor_v1.13.0.zip). I have added a "Text List" panel and "Text List" menu item . To view unique items in this list, use "Not Repeated New Items" menu . I have also added "Save Text List As..." menu item to save this list in XML file. If you do not want to refresh text and information tabs repeatedly for current pointer window, you can uncheck "Always Refresh Tabs On Pointer Movement" menu item.

**Comment by ohyungkr** [comment]
I am so satisfied this release. Thank you.
